things_to_draw = [
    "A creature made of living vines, with flowers blooming along its body, crawling through a dense jungle.",
    "A floating island with a giant clock tower and heavy chains anchoring it to the ground below, with steam-powered airships flying around.",
    "A bookshelf filled with sentient, animated books that have faces and limbs, rearranging themselves according to a complex pattern.",
    "A zombie wearing a tattered Victorian-era hat and coat, holding an old-fashioned lantern, walking through an abandoned amusement park.",
    "A futuristic vending machine that dispenses small, friendly robot companions, each with a unique design and personality.",
    "A giant octopus with cybernetic tentacles emerging from a glowing portal in the middle of a modern city street.",
    "A monster shaped like a pillow with soft, fluffy fur and eyes that glow a gentle blue, lounging in a child's bedroom.",
    "A spaceship piloted by anthropomorphic cats, navigating an asteroid field with ease while sipping alien beverages.",
    "A steampunk dragon with intricate metallic wings and a furnace-like chest, breathing fire mixed with sparks and gears.",
    "A mythical creature with the body of a lion, the wings of an eagle, and the tail of a serpent, perched on a rock in a mystical landscape.",
    "Sunset over a mountain",
    "City skyline at night",
    "Forest in autumn",
    "Beach with palm trees",
    "Desert landscape",
    "Snow-covered village",
    "Underwater coral reef",
    "Space with planets and stars",
    "Medieval castle",
    "Futuristic city",
    "Tropical rainforest",
    "Farm with a barn and animals",
    "Old European street",
    "Japanese garden",
    "Safari with wild animals",
    "Volcano erupting",
    "Waterfall in a jungle",
    "Lighthouse on a cliff",
    "Winter wonderland",
    "Ancient ruins",
    "Carnival with rides",
    "Fairytale forest",
    "Garden with flowers",
    "Zoo with various animals",
    "Island with a lighthouse",
    "Ski resort",
    "Cave interior",
    "Aquarium with marine life",
    "Space station",
    "Pirate ship on the sea",
    "Western desert town",
    "Gothic cathedral",
    "Vineyard in Tuscany",
    "Zen temple",
    "Hot air balloon festival",
    "Grand Canyon",
    "River with boats",
    "Fantasy kingdom",
    "Medieval market",
    "Amusement park",
    "Haunted house",
    "Steampunk city",
    "Mushroom forest",
    "Busy airport",
    "Rocket launch site",
    "Circus tent",
    "Ice cave",
    "Surfing beach",
    "Train station",
    "Watermill in the countryside"
]
